# Site settings
title: Mike Dalton
email: michaelcdalton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I hope to cover many programming and software design topics in this blog.
  This will include languages (Ruby), databases (mongoDB, ElasticSearch) and programming practices (TDD, Refactoring).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mikedalton.co" # the base hostname & protocol for your site
twitter_username: kcdragon_
github_username:  kcdragon
linkedin_username:  michaelcdalton
stackoverflow_username:  kcdragon

# Build settings
markdown: kramdown
exclude:
  - vendor
  - "*.bak"
  - Gemfile
  - Gemfile.lock
  - config.ru
  - Procfile
permalink: pretty

# Tag settings
tag_page_layout: tag_page
tag_page_dir: tag
