# Site settings
title: Mike Dalton
email:
description: > # this means to ignore newlines until "baseurl:"
  Software developer from Philadelphia.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mikedalton.co" # the base hostname & protocol for your site
twitter_username: kcdragon_
instagram_username: kcdragon__
github_username:  kcdragon
linkedin_username:  michaelcdalton
stackoverflow_username:  617090/kcdragon
bluesky_username:  kcdragon.bsky.social

# Build settings
markdown: kramdown
exclude:
  - vendor
  - "*.bak"
  - Gemfile
  - Gemfile.lock
  - config.ru
  - Procfile
permalink: pretty

# Tag settings
tag_page_layout: tag_page
tag_page_dir: tag

theme: jekyll-theme-minimal